In [6]:
%pip install -r requirement.txt

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame({'text':['pepole watch campusx','campusx watch campusx','pepole write comment','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0   pepole watch campusx       1
1  campusx watch campusx       1
2   pepole write comment       0
3  campusx write comment       0

In [13]:
pip install scikit-learn

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.8 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 60.8/60.8 kB 1.1 MB/s eta 0:00:00
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/11.1 MB 6.5 MB/s eta 0:00:02
   - -------------------------------------- 0.5/11.1 MB 5.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/11.1 MB 4.4 MB/s eta 0:00:03
   -- ------------------------------------- 0.7/11.1 MB 3.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/11.1 MB 3.8 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.1 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/11.1 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/11.1 MB 3.2 MB/s eta 0:00:04
   ---- -----


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [15]:
bow = cv.fit_transform(df['text'])   ### crfeat a object

In [16]:
### vocabulary (find unique words)
print(cv.vocabulary_)

{'pepole': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [18]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


### Out of vocabulray problem is solved using this method (BOW)

In [19]:
cv.transform(['campusx watch and write  comment of campusx']).toarray()  ## here more words to be added

array([[2, 1, 0, 1, 1]])

### N GRAMs

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [21]:
nbow = cv.fit_transform(df['text'])   ### crfeat a object

In [22]:
print(cv.vocabulary_)   ## here we are getting 2 words bigrams

{'pepole watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'pepole write': 3, 'write comment': 5, 'campusx write': 1}


#### 3grams

In [23]:

cv = CountVectorizer(ngram_range=(3,3))

In [24]:
bow_3 = cv.fit_transform(df['text'])

In [26]:
print(cv.vocabulary_)

{'pepole watch campusx': 2, 'campusx watch campusx': 0, 'pepole write comment': 3, 'campusx write comment': 1}


### TF-IDF

In [28]:
data = df.copy()
data

text  output
0   pepole watch campusx       1
1  campusx watch campusx       1
2   pepole write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(data['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [33]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'pepole' 'watch' 'write']
